# Generated by Django 4.2.2 on 2023-07-04 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_userprofile_city"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="pin_code",
            new_name="zipcode",
        ),
    ]
