# Generated by Django 4.2.2 on 2023-09-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_rename_pin_code_userprofile_zipcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.SmallIntegerField(
                blank=True, choices=[(1, "Vendor"), (2, "Costumer")], null=True
            ),
        ),
    ]
